// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship['fields'][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship['id']]: ContentRelationshipFieldWithData<
      TSubRelationship['customtypes'],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship['fields'][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship['fields'][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >['id']]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>['id']];

/**
 * Item in *Frontpage → Items*
 */
export interface FrontpageDocumentDataItemsItem {
  /**
   * Product field in *Frontpage → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: frontpage.items[].product
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  product: ContentRelationshipFieldWithData<
    [
      {
        id: 'product';
        fields: [
          'title',
          'description',
          'shopify',
          'primary_image',
          'secondary_image',
          { id: 'gallery'; fields: ['image'] },
        ];
      },
    ]
  >;

  /**
   * Illustration field in *Frontpage → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: frontpage.items[].illustration
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  illustration: ContentRelationshipFieldWithData<
    [{ id: 'illustration'; fields: ['image', 'video'] }]
  >;
}

type FrontpageDocumentDataSlicesSlice = never;

/**
 * Content for Frontpage documents
 */
interface FrontpageDocumentData {
  /**
   * Title field in *Frontpage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Doggy Wear
   * - **API ID Path**: frontpage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Frontpage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: frontpage.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Items field in *Frontpage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: frontpage.items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<FrontpageDocumentDataItemsItem>>;

  /**
   * Slice Zone field in *Frontpage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: frontpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<FrontpageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Frontpage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: frontpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Frontpage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: frontpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Frontpage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: frontpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Frontpage document from Prismic
 *
 * - **API ID**: `frontpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FrontpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FrontpageDocumentData>,
    'frontpage',
    Lang
  >;

/**
 * Content for Illustration documents
 */
interface IllustrationDocumentData {
  /**
   * Image field in *Illustration*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: illustration.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Video field in *Illustration*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: illustration.video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Illustration document from Prismic
 *
 * - **API ID**: `illustration`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IllustrationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<IllustrationDocumentData>,
    'illustration',
    Lang
  >;

type InfopageDocumentDataSlicesSlice = never;

/**
 * Content for Infopage documents
 */
interface InfopageDocumentData {
  /**
   * Title field in *Infopage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: infopage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *Infopage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: infopage.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *Infopage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: infopage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<InfopageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Infopage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: infopage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Infopage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: infopage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Infopage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: infopage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Infopage document from Prismic
 *
 * - **API ID**: `infopage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InfopageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<InfopageDocumentData>,
    'infopage',
    Lang
  >;

/**
 * Item in *Product → Gallery*
 */
export interface ProductDocumentDataGalleryItem {
  /**
   * Image field in *Product → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.gallery[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * Title field in *Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * shopify field in *Product*
   *
   * - **Field Type**: Integration Fields (Catalog: `doggywear--doggy_wear`)
   * - **Placeholder**: *None*
   * - **API ID Path**: product.shopify
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/integration
   */
  shopify: prismic.IntegrationField;

  /**
   * Primary image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.primary_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  primary_image: prismic.ImageField<never>;

  /**
   * Secondary image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.secondary_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  secondary_image: prismic.ImageField<never>;

  /**
   * Gallery field in *Product*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  gallery: prismic.GroupField<Simplify<ProductDocumentDataGalleryItem>>;

  /**
   * Show shipping and packaging info field in *Product*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: product.show_shipping_and_packaging_info
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_shipping_and_packaging_info: prismic.BooleanField;

  /**
   * Show related products field in *Product*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: product.show_related_products
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_related_products: prismic.BooleanField;

  /**
   * Base model field in *Product*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: product.base_model
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  base_model: prismic.SelectField<
    | 'Earth Positive EP19'
    | 'Earth Positive EP185L'
    | 'Earth Positive EP38'
    | 'Earth Positive EP185'
  >; /**
   * Share image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.share_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  share_image: prismic.ImageField<never>;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductDocumentData>,
    'product',
    Lang
  >;

/**
 * Item in *Shipping and Packaging info → Images*
 */
export interface ShippingAndPackagingInfoDocumentDataImagesItem {
  /**
   * Image field in *Shipping and Packaging info → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: shipping_and_packaging_info.images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Shipping and Packaging info documents
 */
interface ShippingAndPackagingInfoDocumentData {
  /**
   * Title field in *Shipping and Packaging info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Packaging & shipping
   * - **API ID Path**: shipping_and_packaging_info.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *Shipping and Packaging info*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: shipping_and_packaging_info.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Images field in *Shipping and Packaging info*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: shipping_and_packaging_info.images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images: prismic.GroupField<
    Simplify<ShippingAndPackagingInfoDocumentDataImagesItem>
  >;
}

/**
 * Shipping and Packaging info document from Prismic
 *
 * - **API ID**: `shipping_and_packaging_info`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ShippingAndPackagingInfoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ShippingAndPackagingInfoDocumentData>,
    'shipping_and_packaging_info',
    Lang
  >;

export type AllDocumentTypes =
  | FrontpageDocument
  | IllustrationDocument
  | InfopageDocument
  | ProductDocument
  | ShippingAndPackagingInfoDocument;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FrontpageDocument,
      FrontpageDocumentData,
      FrontpageDocumentDataItemsItem,
      FrontpageDocumentDataSlicesSlice,
      IllustrationDocument,
      IllustrationDocumentData,
      InfopageDocument,
      InfopageDocumentData,
      InfopageDocumentDataSlicesSlice,
      ProductDocument,
      ProductDocumentData,
      ProductDocumentDataGalleryItem,
      ShippingAndPackagingInfoDocument,
      ShippingAndPackagingInfoDocumentData,
      ShippingAndPackagingInfoDocumentDataImagesItem,
      AllDocumentTypes,
    };
  }
}
