// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/types';
import type * as prismicClient from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship['fields'][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship['id']]: ContentRelationshipFieldWithData<
      TSubRelationship['customtypes'],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship['fields'][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship['fields'][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >['id']]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>['id']];

/**
 * Item in *Front-page → Items*
 */
export interface FrontPageDocumentDataItemsItem {
  /**
   * item field in *Front-page → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: Illustration or Product
   * - **API ID Path**: front-page.items[].item
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  item:
    | prismic.ContentRelationshipField<'product'>
    | prismic.ContentRelationshipField<'illustration'>;
}

/**
 * Item in *Front-page → Secondary items*
 */
export interface FrontPageDocumentDataSecondaryItemsItem {
  /**
   * item field in *Front-page → Secondary items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: front-page.secondary_items[].item
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  item: prismic.ContentRelationshipField<'product'>;
}

/**
 * Content for Front-page documents
 */
interface FrontPageDocumentData {
  /**
   * Share image field in *Front-page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: front-page.share_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  share_image: prismic.ImageField<never>;

  /**
   * Title field in *Front-page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front-page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Front-page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front-page.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Items field in *Front-page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: front-page.items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<FrontPageDocumentDataItemsItem>>;

  /**
   * Secondary title field in *Front-page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front-page.secondary_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  secondary_title: prismic.RichTextField;

  /**
   * Secondary description field in *Front-page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front-page.secondary_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  secondary_description: prismic.RichTextField;

  /**
   * Secondary items field in *Front-page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: front-page.secondary_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  secondary_items: prismic.GroupField<
    Simplify<FrontPageDocumentDataSecondaryItemsItem>
  >;

  /**
   * Instagram title field in *Front-page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front-page.instagram_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  instagram_title: prismic.RichTextField;
}

/**
 * Front-page document from Prismic
 *
 * - **API ID**: `front-page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FrontPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FrontPageDocumentData>,
    'front-page',
    Lang
  >;

/**
 * Content for Illustration documents
 */
interface IllustrationDocumentData {
  /**
   * Image field in *Illustration*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: illustration.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Video field in *Illustration*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: illustration.video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Illustration document from Prismic
 *
 * - **API ID**: `illustration`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IllustrationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<IllustrationDocumentData>,
    'illustration',
    Lang
  >;

/**
 * Content for Info-page documents
 */
interface InfoPageDocumentData {
  /**
   * share_image field in *Info-page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: info-page.share_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  share_image: prismic.ImageField<never>;

  /**
   * title field in *Info-page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info-page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Content field in *Info-page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info-page.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Info-page document from Prismic
 *
 * - **API ID**: `info-page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InfoPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<InfoPageDocumentData>,
    'info-page',
    Lang
  >;

/**
 * Item in *Product → Gallery*
 */
export interface ProductDocumentDataGalleryItem {
  /**
   * Image field in *Product → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.gallery[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * Title field in *Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * shopify field in *Product*
   *
   * - **Field Type**: Integration Fields (Catalog: `doggywear--doggy_wear`)
   * - **Placeholder**: *None*
   * - **API ID Path**: product.shopify
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/integration
   */
  shopify: prismic.IntegrationField;

  /**
   * Primary image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.primary_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  primary_image: prismic.ImageField<never>;

  /**
   * Secondary image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.secondary_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  secondary_image: prismic.ImageField<never>;

  /**
   * Gallery field in *Product*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  gallery: prismic.GroupField<Simplify<ProductDocumentDataGalleryItem>>;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductDocumentData>,
    'product',
    Lang
  >;

export type AllDocumentTypes =
  | FrontPageDocument
  | IllustrationDocument
  | InfoPageDocument
  | ProductDocument;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismicClient.ClientConfig
    ): prismicClient.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismicClient.WriteClientConfig
    ): prismicClient.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismicClient.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FrontPageDocument,
      FrontPageDocumentData,
      FrontPageDocumentDataItemsItem,
      FrontPageDocumentDataSecondaryItemsItem,
      IllustrationDocument,
      IllustrationDocumentData,
      InfoPageDocument,
      InfoPageDocumentData,
      ProductDocument,
      ProductDocumentData,
      ProductDocumentDataGalleryItem,
      AllDocumentTypes,
    };
  }
}
